In [7]:
import numpy as np

In [8]:
kanto = np.array([73,67,43])
weights = np.array([0.3,0.6,0.8])
one = [1,2,3]
two = [4,5,6]
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data2 = np.array([[71, 67, 53],
                         [71, 98, 64],
                         [87, 144, 58],
                         [122, 43, 37],
                         [69, 96, 60]])

In [9]:
kanto

array([73, 67, 43])

In [10]:
type(kanto)

numpy.ndarray

In [11]:
kanto[1]

67

In [12]:
# one * two --> error type of list

In [13]:
kanto * weights

array([21.9, 40.2, 34.4])

In [14]:
np.dot(kanto,weights)

96.5

In [15]:
arr1 = np.array(range(10))
arr2 = np.array(range(10,20))

In [16]:
arr1
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.dot(arr1,arr2)

735

In [18]:
np.dot(one,two)

32

In [19]:
np.matmul(one,two)

32

In [20]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [21]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [22]:
climate_data.shape

(10000, 3)

In [23]:
yields = climate_data @ weights

In [24]:
yields

array([132.3, 106.7, 106.3, ..., 113.3, 136.4, 111.8])

In [25]:
yields.shape

(10000,)

In [26]:
climate_result = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [27]:
climate_result

array([[ 25. ,  76. ,  99. , 132.3],
       [ 39. ,  65. ,  70. , 106.7],
       [ 59. ,  45. ,  77. , 106.3],
       ...,
       [ 99. ,  62. ,  58. , 113.3],
       [ 70. ,  71. ,  91. , 136.4],
       [ 92. ,  39. ,  76. , 111.8]])

In [28]:
a = np.arange(5)

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
a + 20

array([20, 21, 22, 23, 24])

In [31]:
c = np.arange(5)

In [32]:
print(c <= 3)

[ True  True  True  True False]


In [33]:
print(c[c <= 3])

[0 1 2 3]


In [34]:
d = np.linspace(1,10,5)

In [35]:
d

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
e = np.zeros((3,4))

In [37]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
f = np.ones((3,3))

In [39]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
g = np.identity(3)

In [41]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
a

array([0, 1, 2, 3, 4])

In [44]:
c

array([0, 1, 2, 3, 4])

In [53]:
b = np.hstack([a,c])

In [52]:
b

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [54]:
g = np.vstack([a,c])

In [55]:
g

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [57]:
def kuadrat(baris,kolom):
    return kolom**2


In [61]:
h = np.fromfunction(kuadrat,[3,3],dtype=int)

In [62]:
h

array([[0, 1, 4],
       [0, 1, 4],
       [0, 1, 4]])

In [70]:
i = np.random.randint(range(1,10))

In [76]:
i

array([0, 0, 2, 2, 3, 2, 0, 0, 4])

In [78]:
i.max() #nilai max

4

In [81]:
i.argmax() #index max

8

In [87]:
datatype = [('nama','S10'),('tinggi',int)]
data = [
    ('ucup',155),
    ('ahmad',170),
    ('udin',140)
]

In [88]:
data

[('ucup', 155), ('ahmad', 170), ('udin', 140)]

In [89]:
j = np.array(data,dtype=datatype)

In [91]:
print(j)

[(b'ucup', 155) (b'ahmad', 170) (b'udin', 140)]


In [94]:
k = np.dot(a,c)

In [95]:
k

30

In [104]:
x = np.array([2,4,6])
y = np.array([6,9,2])

In [105]:
l = np.cross(x,y)

In [106]:
l # -6 = arah z/-z

array([-46,  32,  -6])

In [118]:
m = np.array([[1,2],
              [4,5]])


In [113]:
m_inv = np.linalg.inv(m)

In [115]:
m_inv

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [116]:
m_det = np.linalg.det(m)

In [117]:
m_det

-2.9999999999999996

In [120]:
n = 1/m_det

In [130]:
o = np.dot(n,np.array([[5,-2],[-4,1]]))

In [132]:
o

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [133]:
# y1 = 2x1 + 3x2 
# y2 = x1 + 2x2
# when x1 = 4, x2=5
# so, y1 = 2(4) + 3(5) = 23
# y2 = 4 + 2(5) = 14

In [142]:
Z = np.array([[2,3],[1,2]])


In [139]:
X = np.array([4,5])

In [144]:
Y = np.dot(Z,X)

In [151]:
Y

array([23, 14])

In [146]:
# when x1 and x2 is not defined
# y1 = 23
# y2 = 14
# [23,14] * (invers from [[2,3],[1,2]]) = [x1,x2]  

In [147]:
Z_inv = np.linalg.inv(Z)

In [154]:
Q = np.dot(Z_inv,Y)

In [155]:
Q #find x1=4, x2=5

array([4., 5.])